version: '3.8'
services:
  products-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    image: products-api:django
    container_name: products-api
    command: runserver 0.0.0.0:8000